# Generated by Django 2.0.2 on 2019-12-24 09:40

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='accounts.Movie', verbose_name='movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.FloatField(blank=True, help_text='review under 5', null=True, validators=[rest_framework.compat.MinValueValidator(0.01), rest_framework.compat.MaxValueValidator(5.0)]),
        ),
    ]
