# Generated by Django 2.0.2 on 2020-01-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200103_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ('-created',), 'verbose_name': 'ContactForm', 'verbose_name_plural': 'ContactForms'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-release_date',)},
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
